# S Parameter extraction for the grating coupler
# Port 1 = left
# Port 2 = top
# Port 2 = right

Port1 = getresult("Exp_h","expansion for Port1");
Port2 = getresult("Exp_v","expansion for Port2");
Port3 = getresult("Exp_h","expansion for Port3");

f = Port1.f;
S11 = Port1.b / Port1.a;
S21 = Port2.a / Port1.a;
S31 = Port3.a / Port1.a;

plot(c/f*1e6,20*log10(abs([S11,S21,S31])),'Wavelength (micron)','Transmission/Reflection (dB)');
legend('|S11|^2','|S21|^2','|S31|^2');

