mode_selection = 1:2;
gap=5e-08;
radius=3e-06;
wg_width=5e-07;
wg_thickness=2.2e-07;
Lc=0;
wavelength_start = 1.5e-6;   
wavelength_stop = 1.6e-6;  
mesh_accuracy=3;

s_filename = "ebeam_dc_halfring_straight_gap=" + num2str(gap*1e9) + "nm_radius=" + num2str(radius*1e6) + "um_width=" + num2str(wg_width*1e9) +  "nm_thickness=" + num2str(wg_thickness*1e9) + "nm_CoupleLength=" + num2str(Lc*1e6)+"um.dat";

ebeam_dc_halfring_straight;

rm("ebeam_dc_halfring_straight.fsp");
rm("ebeam_dc_halfring_straight_S-ParameterMatrixSweep/S-ParameterMatrixSweep_1.fsp");
rm("ebeam_dc_halfring_straight_S-ParameterMatrixSweep/S-ParameterMatrixSweep_2.fsp");
rm("ebeam_dc_halfring_straight_S-ParameterMatrixSweep/S-ParameterMatrixSweep_3.fsp");
rm("ebeam_dc_halfring_straight_S-ParameterMatrixSweep/S-ParameterMatrixSweep_4.fsp");
#exit(2);
