name: Run SiEPIC-Tools Layout tests 

on:
  workflow_dispatch:
  push:
    paths:
      - '**'
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - master


jobs:
  test_layouts:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

        # can also specify python version if needed
      - name: setup python, 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install klayout==0.28.17 numpy scipy pytest pytest-cov SiEPIC

      - name: Test with pytest
        run: pytest --cov=klayout/siepic_ebeam_pdk klayout/siepic_ebeam_pdk  --cov-report=xml
  
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true

      - name: setup python, 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install klayout==0.28.17 numpy scipy pytest pytest-cov SiEPIC

      - name: Test with pytest
        run: pytest klayout/siepic_ebeam_pdk
          
